github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
    
image: 
  file: .gitpod.Dockerfile
tasks:
  - init: |
      yarn install 
      export NODE_OPTIONS="--max-old-space-size=1024" 

vscode:
  extensions:
    - dbaeumer.vscode-eslint
