image: public.ecr.aws/jsii/superchain:1-buster-slim-node18

tasks:
  - name: Install AWS CLI v2
    command: |
      curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
  - name: Install serverless
    command: npm install -g serverless@3.20.0
  - name: Install serverless plugins
    command: yarn install 
